AMREX_HOME  ?= ../../amrex

DEBUG        = FALSE
USE_MPI      = TRUE
USE_OMP      = FALSE
USE_CUDA     = TRUE
COMP         = gnu
DIM          = 3
CXXSTD       = c++17

USE_EB = TRUE
USE_PARTICLES = TRUE

PRINT_NAME   = FALSE
PRINT_LOW   = FALSE
PRINT_HIGH   = FALSE
TIME_DEPENDENT = TRUE


CODE_HOME := ..
include $(CODE_HOME)/Source/Make.Code
