AMREX_HOME  ?= ../amrex

DEBUG        = FALSE
USE_MPI      = TRUE
USE_OMP      = FALSE
USE_CUDA     = FALSE
COMP         = gnu
DIM          = 3
CXXSTD       = c++17


CODE_HOME := ..
include $(CODE_HOME)/Source/Make.Code
