#!/bin/bash
#SBATCH -N 128
#SBATCH -C gpu
#SBATCH -G 512
#SBATCH -J out_gpu512
#SBATCH -q regular
#SBATCH --mail-user=saurabhsawant@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 00:12:00
#SBATCH -A m3766_g
#SBATCH -o gpu512.o%j
#SBATCH -e gpu512.e%j
### SBATCH --reservation=weak_scaling_saurabh


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
#applications may performance better with --gpu-bind=none instead of --gpu-bind=single:1 
srun -n 512 -c 32 --cpu_bind=cores -G 512 --gpu-bind=single:1  ./../../../Exec/main3d.gnu.TPROF.MPI.CUDA.EB.TD.TRAN.BROYPRLL.ex ../../../input/scaling/weak_overall/equilibrium/gpu512
