AMREX_HOME  ?= ../../../../../amrex

DEBUG        = FALSE
ASSERT       = FALSE
USE_MPI      = TRUE
USE_OMP      = FALSE
USE_CUDA     = TRUE
COMP         = gnu
DIM          = 3
CXXSTD       = c++17
TINY_PROFILE   = TRUE

LIBRARIES = -lcublas

CODE_HOME := ..
include $(CODE_HOME)/Source/Make.Code
