#!/bin/bash
#SBATCH -N 64
#SBATCH -C gpu
#SBATCH -G 256
#SBATCH -J 256gpu
#SBATCH -q regular
#SBATCH --mail-user=saurabhsawant@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 00:02:00
#SBATCH -A m3766_g
#SBATCH -o W256C1.o%j
#SBATCH -e W256C1.e%j
### SBATCH --reservation=weak_scaling_saurabh


#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=true

#run the application:
#applications may performance better with --gpu-bind=none instead of --gpu-bind=single:1 
srun -n 256 -c 32 --cpu_bind=cores -G 256 --gpu-bind=single:1  ./../Exec/main3d.gnu.MPI.CUDA.ex input_256gpu
