AMREX_HOME  ?= ../../../../../amrex

DEBUG        = FALSE
ASSERT       = FALSE
USE_MPI      = TRUE
USE_OMP      = FALSE
USE_CUDA     = FALSE
COMP         = gnu
DIM          = 3
CXXSTD       = c++17
GPU_MATRIX_OP = TRUE
TINY_PROFILE   = TRUE

PRINT_NAME   = FALSE
PRINT_LOW   = FALSE
PRINT_HIGH   = FALSE

CODE_HOME := ..
include $(CODE_HOME)/Source/Make.Code
